version: '3.7'
services:
  syncdata:
    build:
      args:
        env: wc
      context: .
      dockerfile: deployments/syncdata.Dockerfile
    image: syncdata:latest
    restart: always
    container_name: syncdata
    environment:
      PLATFORM: ${PLATFORM}
      RABBITMQ_ADDRESS: ${RABBITMQ_ADDRESS}
      VIRTUAL_HOSTS: ${VIRTUAL_HOSTS}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Taipei
    ports:
      - 6007:6007
networks:
  default:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.114.0.0/16
